# Generated by Django 3.1.4 on 2021-04-02 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_contactdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdata',
            old_name='yourname',
            new_name='name',
        ),
    ]
