# Generated by Django 3.1.4 on 2021-04-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210401_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.CharField(max_length=300),
        ),
    ]
