# Generated by Django 3.1.4 on 2021-04-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_service_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(max_length=300),
        ),
    ]
