FROM ubuntu:18.04
RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get install -y vim
RUN apt-get install -y curl
RUN apt-get install -y apache2 
RUN apt-get install -y apache2-utils
RUN apt-get install -y python3 libapache2-mod-wsgi-py3
RUN ln /usr/bin/python3 /usr/bin/python
RUN apt-get install -y python3-pip 
RUN ln /usr/bin/pip3 /usr/bin/pip
RUN pip install --upgrade pip
RUN pip install django ptvsd
ADD ./coder_cafe_site.conf /etc/apache2/sites-available/000-default.conf
EXPOSE 80
CMD ["apache2ctl", "-D", "FOREGROUND"]

# COPY requirements.txt  requirements.txt
# RUN pip3 install -r requirements.txt
# COPY . .

# CMD [ "python3", "apache2ctl","-D", "runserver","FOREGROUND", "0.0.0.0:8000"] 